# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69b39109538c9a2b608e222a38c9b07f0d33f6e30408733ef16f39ce0f42f7810093db1d5b5c075cd52656e1b7885ffc0f7517fb63800b377ab27d94a52a1cdd

test:
  secret_key_base: a4370da2b53d5a535ff7393085fd0b3b924053103483f5105182282e42d155866c77bd7ebf84a2ed06460e0ca94e1d8441c88873e9b7d98f7d9ea79c9ad0b0df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
