# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

schools = School.create([{name: "University of Central Florida", logo: "https://recruit-match.ncsasports.org/fasttrack/clientimages/15601college.jpg", mascot_name: "Knights", ipeds_id: 132903},
{name:"University of Michigan", logo: "https://recruit-match.ncsasports.org/fasttrack/clientimages/15654college.jpg", mascot_name: "Wolverines", ipeds_id: 170976, zip: '48109'},
{name:"Vanderbilt University", logo: "https://recruit-match.ncsasports.org/fasttrack/clientimages/15781college.jpg", mascot_name: "Commodores", ipeds_id: 221999},
{name:"University of California - San Diego", zip: '92093', logo: "https://recruit-match.ncsasports.org/fasttrack/clientimages/15596college.jpg", mascot_name: "Tritons", ipeds_id: 110680},
{name:"Pittsburg State University", zip: '66762', logo: "https://recruit-match.ncsasports.org/fasttrack/clientimages/15172college.jpg", mascot_name: "Gorillas", ipeds_id: 155681},
{name:"Delta State University", zip: '38733', logo: "https://recruit-match.ncsasports.org/fasttrack/clientimages/14333college.jpg", mascot_name: "Fighting Okra", ipeds_id: 175616},
{name:"Cardinal Stritch University", zip: '53217', logo: "https://recruit-match.ncsasports.org/fasttrack/clientimages/14086college.jpg", mascot_name: "Wolves", ipeds_id: 238430},
{name:"Georgetown College", logo: "https://recruit-match.ncsasports.org/fasttrack/clientimages/14490college.jpg", mascot_name: "Tigers", ipeds_id: 156745},
{name:"Huntington University", logo: "https://recruit-match.ncsasports.org/fasttrack/clientimages/14599college.jpg", mascot_name: "Foresters", ipeds_id: 150941},
{name:"Kansas City Kansas Community College", logo: "https://recruit-match.ncsasports.org/fasttrack/clientimages/14673college.jpg", mascot_name: "Blue Devils", ipeds_id: 155292}])


#  id                     :integer          not null, primary key
#  season                 :integer
#  school_size            :integer
#  location_type          :integer
#  zip                    :string
#  sport_id               :integer
#  sport_acedemic_balance :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  school_id              :integer          not null

school_preference_maps = SchoolPreferenceMap.create(
  [{ school_id: School.find_by(ipeds_id: 132903).id, season: 1, school_size: 1, location_type: 2, sport_acedemic_balance: 1 },
  { school_id: School.find_by(ipeds_id: 170976).id, season: 2, school_size: 1, location_type: 1, sport_acedemic_balance: 0 },
  { school_id: School.find_by(ipeds_id: 221999).id, season: 2, school_size: 1, location_type: 1, sport_acedemic_balance: 0 },
  { school_id: School.find_by(ipeds_id: 110680).id, season: 1, school_size: 1, location_type: 2, sport_acedemic_balance: 0 },
  { school_id: School.find_by(ipeds_id: 155681).id, season: 0, school_size: 2, location_type: 2, sport_acedemic_balance: 0 },
  { school_id: School.find_by(ipeds_id: 175616).id, season: 1, school_size: 2, location_type: 0, sport_acedemic_balance: 1 },
  { school_id: School.find_by(ipeds_id: 238430).id, season: 0, school_size: 2, location_type: 0, sport_acedemic_balance: 1 },
  { school_id: School.find_by(ipeds_id: 156745).id, season: 2, school_size: 0, location_type: 2, sport_acedemic_balance: 1 },
  { school_id: School.find_by(ipeds_id: 150941).id, season: 0, school_size: 0, location_type: 2, sport_acedemic_balance: 1 },
  { school_id: School.find_by(ipeds_id: 155292).id, season: 2, school_size: 0, location_type: 1, sport_acedemic_balance: 1 }])

college_sport_coaches = CollegeSportCoach.create(
[
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"Derek Woelffer",coach_position:"Assistant Coach",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"Drew Diener",coach_position:"Head Coach",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"Glen Heffernan",coach_position:"Asst. Coach",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"Mike Jaskulski",coach_position:"Head Coach",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"Nick Ford",coach_position:"Graduate Assistant",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"JT  Thompson",coach_position:"Head Coach",sport_name:"Men's Golf", sport_id: 17660},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"Ben Shepherd",coach_position:"Assistant Coach",sport_name:"Men's Soccer", sport_id: 17683},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"Jamie Bladen",coach_position:"Assistant Coach",sport_name:"Men's Soccer", sport_id: 17683},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"Kevin Brennan",coach_position:"Head Coach",sport_name:"Men's Soccer", sport_id: 17683},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"Natalie Wildes",coach_position:"Head",sport_name:"Men's Volleyball", sport_id: 17695},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"Shane Spellman",coach_position:"Asst. Coach ",sport_name:"Men's Volleyball", sport_id: 17695},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"Jenny Fuller",coach_position:"Head Coach",sport_name:"Softball", sport_id: 17634},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"John Pfaffl",coach_position:"Head",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"Mark Maley",coach_position:"Assistant Coach",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"Rich Panella",coach_position:"Head ",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"Sara Bayer",coach_position:"Assistant Coach",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"JT  Thompson",coach_position:"Head Coach",sport_name:"Women's Golf", sport_id: 17660},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"Heather Roadhouse",coach_position:"Assistant Coach",sport_name:"Women's Soccer", sport_id: 17684},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"Kevin Brennan",coach_position:"Head Coach",sport_name:"Women's Soccer", sport_id: 17684},
  {college_name:"Cardinal Stritch University",school_id: School.find_by(name: "Cardinal Stritch University").id, coach_name:"Natalie Wildes",coach_position:"Head",sport_name:"Women's Volleyball", sport_id: 17696},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Cable McMinn",coach_position:"Grad Asst.",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Eric Patten",coach_position:"Asst.",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Mike Kinnison",coach_position:"Head",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Stephen Waggener",coach_position:"Asst.",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Bam Bryant",coach_position:"WR Coach",sport_name:"Football", sport_id: 17633},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Charles Anthony",coach_position:"Defensive Coordinator",sport_name:"Football", sport_id: 17633},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Colin Johnson",coach_position:"Assistant Coach",sport_name:"Football", sport_id: 17633},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Joel Williams",coach_position:"Associate Head Coach/Offensive Coordinator",sport_name:"Football", sport_id: 17633},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Joiner Stewart",coach_position:"Assistant Coach",sport_name:"Football", sport_id: 17633},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Jonathon Fletcher",coach_position:"TE Coach",sport_name:"Football", sport_id: 17633},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Kelvin Green",coach_position:"DL Coach",sport_name:"Football", sport_id: 17633},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Kevin Peters",coach_position:"Safeties Coach",sport_name:"Football", sport_id: 17633},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Lanier Goethie",coach_position:"Assistant Coach",sport_name:"Football", sport_id: 17633},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Nick Popiel",coach_position:"Assistant Coach",sport_name:"Football", sport_id: 17633},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Todd Cooley",coach_position:"Head Coach",sport_name:"Football", sport_id: 17633},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Travis Champion",coach_position:"Assistant Coach",sport_name:"Football", sport_id: 17633},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Tyler Hasty",coach_position:"Assistant Coach",sport_name:"Football", sport_id: 17633},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Jay Bowen",coach_position:"Asst. Coach ",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Jim Boone",coach_position:"Head Coach",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Robert Szorc",coach_position:"",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Sam Dunning",coach_position:"Head",sport_name:"Men's Golf", sport_id: 17660},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Andy Robertson",coach_position:"Head Coach",sport_name:"Men's Soccer", sport_id: 17683},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Conor  Hurley",coach_position:"Asst. Coach ",sport_name:"Men's Soccer", sport_id: 17683},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Casey Bourgoyne",coach_position:"Head",sport_name:"Softball", sport_id: 17634},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Dave Martinez",coach_position:"Assist.",sport_name:"Softball", sport_id: 17634},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Craig Roden",coach_position:"Head Coach",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Mechan Vanderpool",coach_position:"Assistant",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Sandra Rushing",coach_position:"Head ",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Shameka Russell",coach_position:"Assistant Coach",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Delta State University", school_id: School.find_by(name: "Delta State University").id, coach_name:"Paul Babba",coach_position:"Head",sport_name:"Women's Soccer", sport_id: 17684},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Adam Skonieczki",coach_position:"Rec. Coord.",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Josh Franklin",coach_position:"Asst.",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Micah Baumfeld",coach_position:"Head",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Bill Cronin",coach_position:"HC",sport_name:"Football", sport_id: 17633},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Brian Landis",coach_position:"DB/RC",sport_name:"Football", sport_id: 17633},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Bruce Owens",coach_position:"Asst./DL ",sport_name:"Football", sport_id: 17633},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Dwayne  Ellison",coach_position:"Sec.",sport_name:"Football", sport_id: 17633},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"James Dummer",coach_position:"K",sport_name:"Football", sport_id: 17633},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Marty   Park",coach_position:"WR",sport_name:"Football", sport_id: 17633},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Michael Caba",coach_position:"Offensive Coordinator",sport_name:"Football", sport_id: 17633},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Nathan Peniston",coach_position:"Off. Skill",sport_name:"Football", sport_id: 17633},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Shan Housekeeper",coach_position:"DC/LB/ST",sport_name:"Football", sport_id: 17633},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Steve  Hill",coach_position:"OL",sport_name:"Football", sport_id: 17633},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Chris Briggs",coach_position:"HC",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"James Jackson",coach_position:"Asst.",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Flash Williams",coach_position:"Head",sport_name:"Men's Golf", sport_id: 17660},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Derek Willis",coach_position:"Head Coach",sport_name:"Men's Soccer", sport_id: 17683},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Trip Rogers",coach_position:"Assistant Coach",sport_name:"Men's Soccer", sport_id: 17683},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Bryan Johnson",coach_position:"Assist.",sport_name:"Softball", sport_id: 17634},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Thomas Thornton",coach_position:"Head",sport_name:"Softball", sport_id: 17634},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Andrea McCloskey",coach_position:"Head Coach",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Flash Williams",coach_position:"Head",sport_name:"Women's Golf", sport_id: 17660},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Leah Crews Castleman",coach_position:"Head",sport_name:"Women's Soccer", sport_id: 17684},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Felicia Pace",coach_position:"Asst. Coach",sport_name:"Women's Volleyball", sport_id: 17696},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Nick Griffin",coach_position:"Head",sport_name:"Women's Volleyball", sport_id: 17696},
  {college_name:"Georgetown College", school_id: School.find_by(name: "Georgetown College").id, coach_name:"Tori Verville",coach_position:"Asst. Coach",sport_name:"Women's Volleyball", sport_id: 17696},
  {college_name:"Huntington University", school_id: School.find_by(name: "Huntington University").id, coach_name:"Mike Frame",coach_position:"Head",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Huntington University", school_id: School.find_by(name: "Huntington University").id, coach_name:"Thad Frame",coach_position:"",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Huntington University", school_id: School.find_by(name: "Huntington University").id, coach_name:"Mark Green",coach_position:"Asst coach",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Huntington University", school_id: School.find_by(name: "Huntington University").id, coach_name:"Ty Platt",coach_position:"Head",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Huntington University", school_id: School.find_by(name: "Huntington University").id, coach_name:"Rick Sholund",coach_position:"Head Coach",sport_name:"Men's Golf", sport_id: 17660},
  {college_name:"Huntington University", school_id: School.find_by(name: "Huntington University").id, coach_name:"Terry  Herrell",coach_position:"Asst. Coach ",sport_name:"Men's Golf", sport_id: 17660},
  {college_name:"Huntington University", school_id: School.find_by(name: "Huntington University").id, coach_name:"Russ Lawson",coach_position:"Head",sport_name:"Men's Soccer", sport_id: 17683},
  {college_name:"Huntington University", school_id: School.find_by(name: "Huntington University").id, coach_name:"Doug Gower",coach_position:"Head Coach",sport_name:"Softball", sport_id: 17634},
  {college_name:"Huntington University", school_id: School.find_by(name: "Huntington University").id, coach_name:"Lonnie Snyder",coach_position:"Assistant Coach",sport_name:"Softball", sport_id: 17634},
  {college_name:"Huntington University", school_id: School.find_by(name: "Huntington University").id, coach_name:"Pete Eckert",coach_position:"Assistant Coach",sport_name:"Softball", sport_id: 17634},
  {college_name:"Huntington University", school_id: School.find_by(name: "Huntington University").id, coach_name:"Jake Johnson",coach_position:"",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Huntington University", school_id: School.find_by(name: "Huntington University").id, coach_name:"Lori Culler",coach_position:"Head",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Huntington University", school_id: School.find_by(name: "Huntington University").id, coach_name:"Pete Schownir",coach_position:"Head Coach",sport_name:"Women's Golf", sport_id: 17660},
  {college_name:"Huntington University", school_id: School.find_by(name: "Huntington University").id, coach_name:"Chris Tillett",coach_position:"Head Coach",sport_name:"Women's Soccer", sport_id: 17684},
  {college_name:"Huntington University", school_id: School.find_by(name: "Huntington University").id, coach_name:"Kyle Shondell",coach_position:"Head Coach ",sport_name:"Women's Volleyball", sport_id: 17696},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Billy  Sharp",coach_position:"Assistant Coach",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Jason Browar",coach_position:"Assistant Baseball Coach",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Matt Goldbeck",coach_position:"Facilties Coordinator/Associate Head Baseball Coach",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Steve  Burleson",coach_position:"Head Coach",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Steve Burleson",coach_position:"Head Coach",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Joe McKinstry",coach_position:"Asst.",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Kelly Newton",coach_position:"Head Coach",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Gary Schrader",coach_position:"Head Golf Coach",sport_name:"Men's Golf", sport_id: 17660},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Burke Slusher",coach_position:"Assistant Men's Soccer Coach",sport_name:"Men's Soccer", sport_id: 17683},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Ruben Rodriguez",coach_position:"Head",sport_name:"Men's Soccer", sport_id: 17683},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Kacy Tillery",coach_position:"Head",sport_name:"Softball", sport_id: 17634},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Tiffany Jennings",coach_position:"Assistant Softball Coach",sport_name:"Softball", sport_id: 17634},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Chamissa Anderson",coach_position:"Asst. Coach",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Dawn Adams",coach_position:"Vol. Asst. Coach ",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Joe McKinstry",coach_position:"Head Coach",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Jeremy Winzer",coach_position:"Head Coach",sport_name:"Women's Soccer", sport_id: 17684},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Melanie Pickert",coach_position:"Asst. Coach",sport_name:"Women's Soccer", sport_id: 17684},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Dee Bruno",coach_position:"Assistant Volleyball Coach",sport_name:"Women's Volleyball", sport_id: 17696},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"Mary Bruno",coach_position:"Head Coach",sport_name:"Women's Volleyball", sport_id: 17696},
  {college_name:"Kansas City Kansas Community College", school_id: School.find_by(name: "Kansas City Kansas Community College").id, coach_name:"paloma juarez",coach_position:"Assistant Coach",sport_name:"Women's Volleyball", sport_id: 17696},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Matt Murray",coach_position:"Head Coach",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Carl Roth",coach_position:"Asst./LB",sport_name:"Football", sport_id: 17633},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Dave Wiemers",coach_position:"Asst. HC / DC",sport_name:"Football", sport_id: 17633},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Derrick Sherman",coach_position:"Assistant Coach / Wide Receivers",sport_name:"Football", sport_id: 17633},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"John Pierce",coach_position:"Asst./RB",sport_name:"Football", sport_id: 17633},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Lance Cullen",coach_position:"Asst./ Defensive Secondary",sport_name:"Football", sport_id: 17633},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Larry Garman",coach_position:"Assistant Coach / Off-Campus Recruiting",sport_name:"Football", sport_id: 17633},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Neal Philpot",coach_position:"Asst./WR",sport_name:"Football", sport_id: 17633},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Ryan Hellwig",coach_position:"Asst./DL",sport_name:"Football", sport_id: 17633},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Steve Rampy",coach_position:"Asst./OC",sport_name:"Football", sport_id: 17633},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Steve Wells",coach_position:"Asst./OL",sport_name:"Football", sport_id: 17633},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Tim  Beck",coach_position:"Head",sport_name:"Football", sport_id: 17633},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Kevin Muff",coach_position:"Head Coach",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Preston Ingram",coach_position:"Asst.",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Ryan Stock",coach_position:"Assistant",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Brad  Wells",coach_position:"Assistant Athletic Director",sport_name:"Men's Golf", sport_id: 17660},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Elizabeth Economon",coach_position:"Head Coach",sport_name:"Softball", sport_id: 17634},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Amanda Davied",coach_position:"Assistant Coach",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Lane Lord",coach_position:"Head Coach",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Jenny Mueller",coach_position:"Head Coach",sport_name:"Women's Volleyball", sport_id: 17696},
  {college_name:"Pittsburg State University",  school_id: School.find_by(name: "Pittsburg State University").id ,coach_name:"Skye Wade",coach_position:"Assistant Coach",sport_name:"Women's Volleyball", sport_id: 17696},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Eric Newman",coach_position:"Head",sport_name:"Baseball", sport_id: 17706},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"J.T. Bloodworth",coach_position:"Asst.",sport_name:"Baseball", sport_id: 17706},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Jeff Calhoon",coach_position:"Asst.",sport_name:"Baseball", sport_id: 17706},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Nick La Face",coach_position:"Assistant Coach",sport_name:"Baseball", sport_id: 17706},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Rob Avila",coach_position:"Asst.",sport_name:"Baseball", sport_id: 17706},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Brendan Clowry",coach_position:"Assistant Coach",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Clint Allard",coach_position:"Associate Head Coach",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Eric Olen",coach_position:"Head Coach",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Terry Ryan",coach_position:"Assistant Coach",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Jim Ragan",coach_position:"Head Coach",sport_name:"Men's Golf", sport_id: 17660},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Lewis Simon",coach_position:"Asst. Coach",sport_name:"Men's Golf", sport_id: 17660},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Jon Pascale",coach_position:"Head Coach",sport_name:"Men's Soccer", sport_id: 17683},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Ryan  Hernandez",coach_position:"Associate Head",sport_name:"Men's Soccer", sport_id: 17683},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Tim Hogan",coach_position:"Assistant/ Goalkeepers",sport_name:"Men's Soccer", sport_id: 17683},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Chris Webb",coach_position:"Asst. Coach",sport_name:"Men's Volleyball", sport_id: 17695},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Kevin Ring",coach_position:"Head Men's Volleyball Coach",sport_name:"Men's Volleyball", sport_id: 17695},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Kyle Campana",coach_position:"Asst.",sport_name:"Men's Volleyball", sport_id: 17695},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Jessica Millsap",coach_position:"RC",sport_name:"Softball", sport_id: 17634},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Patti Gerckens",coach_position:"Head Coach",sport_name:"Softball", sport_id: 17634},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Chelsea Carlisle",coach_position:"Assistant Coach",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Heidi Heintz",coach_position:"Asst. Coach",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Heidi VanDerveer",coach_position:"Head Coach",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Brian McManus",coach_position:"Head Women's Soccer Coach",sport_name:"Women's Soccer", sport_id: 17684},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Kristin Jones",coach_position:"Asst.",sport_name:"Women's Soccer", sport_id: 17684},
  {college_name:"University of California - San Diego", school_id: School.find_by(name: "University of California - San Diego").id, coach_name:"Sean Cahill",coach_position:"Assistant Coach",sport_name:"Women's Volleyball", sport_id: 17696},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Andy Chriscaden",coach_position:"Volunteer Assistant Coach",sport_name:"Baseball", sport_id: 17706},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Brandon  Romans",coach_position:"Asst. Coach",sport_name:"Baseball", sport_id: 17706},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Ryan Breen",coach_position:"Director of Baseball Operations",sport_name:"Baseball", sport_id: 17706},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Ryan Klosterman",coach_position:"Asst.",sport_name:"Baseball", sport_id: 17706},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Terry Rooney",coach_position:"Head",sport_name:"Baseball", sport_id: 17706},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Allen  Mogridge",coach_position:"Offensive Line",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Andrew  Thacker",coach_position:"Safeties Coach",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Brent  Key",coach_position:"OC/RB",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Chuck  Bresnahan",coach_position:"DC/ LB Coach ",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Danielle Key",coach_position:"Senior Administrative Assistant",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Danny Barrett",coach_position:"Quarterbacks Coach",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Keegan Kennedy",coach_position:"Tight Ends/H-Backs/Special Teams",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Lorenzo Costantitni",coach_position:"DL",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Marty O'Leary",coach_position:"DFO",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Megan Taylor",coach_position:"Administrative Assistant",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Mike Buscemi",coach_position:"Director of Player Personnel",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Scott  Frost",coach_position:"Head Coach",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Sean Beckton",coach_position:"WR",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Travis  Fisher",coach_position:"Cornerbacks",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"UCF Football",coach_position:"Football Recruiting",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Christian Webster",coach_position:"Assistant Coach",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Darren Tillis",coach_position:"Assistant",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Donnie Jones",coach_position:"Head",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Shawn Finney",coach_position:"Assistant",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Tim Thomas",coach_position:"Assistant",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Bryce Wallor",coach_position:"Head",sport_name:"Men's Golf", sport_id: 17660},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Akai Jackson",coach_position:"Strength & Conditioning Coach",sport_name:"Men's Lacrosse", sport_id: 17707},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"James Foote",coach_position:"Head Coach",sport_name:"Men's Lacrosse", sport_id: 17707},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Phil Vanderau",coach_position:"Assistant Coach/Recruiting Coordinator",sport_name:"Men's Lacrosse", sport_id: 17707},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Bryan Cunningham",coach_position:"Head",sport_name:"Men's Soccer", sport_id: 17683},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Joel Tyson",coach_position:"Assistant Coach",sport_name:"Men's Soccer", sport_id: 17683},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Will Clayton",coach_position:"Assistant ",sport_name:"Men's Soccer", sport_id: 17683},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Hillary Barrow",coach_position:"Assistant",sport_name:"Softball", sport_id: 17634},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Renee  Gillispie",coach_position:"Head Coach",sport_name:"Softball", sport_id: 17634},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Tiffany  Patteson",coach_position:"Assistant Coach",sport_name:"Softball", sport_id: 17634},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Joe Silvestri",coach_position:"Asst. Coach ",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Joi Williams",coach_position:"Head Coach",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Karen Del Carpio",coach_position:"Assistant Director of Women's Basketball Operations",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Ken  Griffin",coach_position:"Asst. Coach ",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Kim Boes",coach_position:"Director of Basketball Operations",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Tamisha Augustin",coach_position:"Recruiting Coordinator ",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Emily Marron",coach_position:"Head Coach",sport_name:"Women's Golf", sport_id: 17660},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Steve Sims",coach_position:"Assist.",sport_name:"Women's Golf", sport_id: 17660},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Jamie Corti",coach_position:"Assistant Coach",sport_name:"Women's Soccer", sport_id: 17684},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Tiffany Sahaydak",coach_position:"Head Coach",sport_name:"Women's Soccer", sport_id: 17684},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Tim Sahaydak",coach_position:"Associate Head Coach",sport_name:"Women's Soccer", sport_id: 17684},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Erik Peterson",coach_position:"Assist.",sport_name:"Women's Volleyball", sport_id: 17696},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Michelle Chatman",coach_position:"Assistant Head Coach",sport_name:"Women's Volleyball", sport_id: 17696},
  {college_name:"University of Central Florida", school_id: School.find_by(name: "University of Central Florida").id ,coach_name:"Todd Dagenais",coach_position:"Head",sport_name:"Women's Volleyball", sport_id: 17696},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Erik Bakich",coach_position:"Head",sport_name:"Baseball", sport_id: 17706},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Nick Schnabel",coach_position:"Rec. Coord.",sport_name:"Baseball", sport_id: 17706},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Sean  Kenny",coach_position:"Asst.",sport_name:"Baseball", sport_id: 17706},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Chris  Partridge",coach_position:"Recruiting Coordinator",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"D.J. Durkin",coach_position:"DC/ LB",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Football  Recruiting",coach_position:"Recruiting Operations ",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Greg  Jackson",coach_position:"Secondary ",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Greg Mattison",coach_position:"DL",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Jedd Fisch",coach_position:"Pass Game Coordinator/QB/WR",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Jim Harbaugh",coach_position:"Head Coach",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"John Baxter",coach_position:"ST",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Mary Passink",coach_position:"Administrative Assistant to the Head Coach for Recruiting",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Tyrone Wheatley",coach_position:"RB",sport_name:"Football", sport_id: 17633},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Jeff Meyer",coach_position:"Assistant Coach",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"John  Beilein",coach_position:"Asst. ",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"John Beilein",coach_position:"Head",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Recruiting Coordinators",coach_position:"Recruiting Inbox",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Chris Whitten",coach_position:"Head",sport_name:"Men's Golf", sport_id: 17660},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Nick Pumford",coach_position:"Assist.",sport_name:"Men's Golf", sport_id: 17660},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Conor Ford",coach_position:"Assistant Coach",sport_name:"Men's Lacrosse", sport_id: 17707},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"John Paul",coach_position:"Head",sport_name:"Men's Lacrosse", sport_id: 17707},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Ken Broschart",coach_position:"Assistant Coach",sport_name:"Men's Lacrosse", sport_id: 17707},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Chaka Daley",coach_position:"Head Coach",sport_name:"Men's Soccer", sport_id: 17683},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Bonnie Tholl",coach_position:"Associate Head",sport_name:"Softball", sport_id: 17634},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Carol Hutchins",coach_position:"Head Coach",sport_name:"Softball", sport_id: 17634},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Joy McCorvey",coach_position:"Asst",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Kim  Barnes Arico",coach_position:"Head Coach",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Megan  Duffy",coach_position:"Asst. Coach ",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Melanie  Moore ",coach_position:"Asst. Coach ",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Jan Dowling",coach_position:"Head",sport_name:"Women's Golf", sport_id: 17660},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Greg Ryan",coach_position:"Head",sport_name:"Women's Soccer", sport_id: 17684},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Erin Virtue",coach_position:"Assistant Coach",sport_name:"Women's Volleyball", sport_id: 17696},
  {college_name:"University of Michigan", school_id: School.find_by(name: "University of Michigan").id ,coach_name:"Mark Rosen",coach_position:"Head Women's Volleyball Coach",sport_name:"Women's Volleyball", sport_id: 17696},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"David Macias",coach_position:"Volunteer Coach",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Keri Richardson",coach_position:"Administrative Assistant",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Scott Brown",coach_position:"Assistant Coach",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Tim Corbin",coach_position:"Head",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Travis Jewett",coach_position:"Asst.",sport_name:"Baseball", sport_id: 17706},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Brent Maxie",coach_position:"Secondary",sport_name:"Football", sport_id: 17633},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Charles Bankins",coach_position:"ST/RB",sport_name:"Football", sport_id: 17633},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"David Kotulski",coach_position:"DC/LB",sport_name:"Football", sport_id: 17633},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Derek Mason",coach_position:"Head Coach",sport_name:"Football", sport_id: 17633},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Frank Maile",coach_position:"DL",sport_name:"Football", sport_id: 17633},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Kenwick Thompson",coach_position:"OLB",sport_name:"Football", sport_id: 17633},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Keven Lightner",coach_position:"OL",sport_name:"Football", sport_id: 17633},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Marc Lubick",coach_position:"WR",sport_name:"Football", sport_id: 17633},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Matt Britain",coach_position:"Asst. DFO",sport_name:"Football", sport_id: 17633},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Matt Ruland",coach_position:"Recruiting Assistant",sport_name:"Football", sport_id: 17633},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Tosin Abari",coach_position:"Player Dev.",sport_name:"Football", sport_id: 17633},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Tyler Barnes",coach_position:"Player Personnel",sport_name:"Football", sport_id: 17633},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Adam Cohen",coach_position:"Asst. ",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Dan Cage",coach_position:"Director of Basketball Operations",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Debbie Green",coach_position:"Administrative Assistant",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Kevin Stallings",coach_position:"Head Coach",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Tom Richardson",coach_position:"Assistant Coach",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Yanni Hufnagel",coach_position:"Assistant Coach",sport_name:"Men's Basketball", sport_id: 17638},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Scott Limbaugh",coach_position:"Head Coach",sport_name:"Men's Golf", sport_id: 17660},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Beth Hewitt",coach_position:"Assistant Coach",sport_name:"Men's Lacrosse", sport_id: 17707},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"George MacLellan",coach_position:"Director of Video Operations",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Jon Erickson",coach_position:"Director of Basketball Operations",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Kim Rosamond",coach_position:"Asst.",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Melanie Balcomb",coach_position:"Head Women's Basketball Coach",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Vicki Spina",coach_position:"Administrative Assistant",sport_name:"Women's Basketball", sport_id: 17639},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Greg Allen",coach_position:"Head Coach",sport_name:"Women's Golf", sport_id: 17660},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Holly Clark",coach_position:"Assistant Coach",sport_name:"Women's Golf", sport_id: 17660},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Darren Ambrose",coach_position:"Head",sport_name:"Women's Soccer", sport_id: 17684},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Jonnice  Wilcox ",coach_position:"Asst. Coach",sport_name:"Women's Soccer", sport_id: 17684},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Kelly  Keelan",coach_position:"Asst. Coach ",sport_name:"Women's Soccer", sport_id: 17684},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Ken  Mashur",coach_position:"Asst. Coach ",sport_name:"Women's Soccer", sport_id: 17684},
  {college_name:"Vanderbilt University", school_id: School.find_by(name: "Vanderbilt University").id, coach_name:"Kyle  Roelke",coach_position:"Asst. Coach ",sport_name:"Women's Soccer", sport_id: 17684}
]
)
